services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: storybook_frontend
    environment:
      VITE_API_PROXY_TARGET: ${VITE_API_PROXY_TARGET}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: storybook_backend
    env_file:
      - ./.env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - minio
      - redis

  redis:
    image: redis:7-alpine
    container_name: storybook_redis
    ports:
      - "${REDIS_PORT}:6379"

  minio:
    image: ${MINIO_IMAGE}
    container_name: storybook_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  pgweb:
    image: ${PGWEB_IMAGE}
    container_name: storybook_pgweb
    environment:
      PGWEB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "${PGWEB_PORT}:8081"
    depends_on:
      - db

  db:
    image: ${POSTGRES_IMAGE}
    container_name: storybook_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  minio_data:
